### ISSUE TITLE
Create installers

### ISSUE THREAD

**Issue by jdestgermain** [CharaChorder/nexus#48]
instead of just running exe

**Comment by Raymo111** [comment]
Also put the SQLite file in a proper location:
- `%APPDATA%` on Windows
- `~/Library/<Nexus folder>/` on MacOS
- `$XDG_CONFIG_HOME` on *nix

**Comment by GetPsyched** [comment]
> `$XDG_CONFIG_HOME` on *nix

It should be `$XDG_DATA_HOME` for anything that isn't configuration. Ideally, we should not store configuration and the state of the app (chord logs in this case) in the same database.

So, ideally, config would go into `$XDG_CONFIG_HOME/nexus.conf` and any data/state will go in `$XDG_DATA_HOME/nexus/`.

> on *nix

Also, this is for Linux, not just NixOS :P

**Comment by GetPsyched** [comment]
Also, @jdestgermain, what's wrong with the current exe approach? I'm personally biased against installers as they provide little value. The most significant thing I'd say installers help in is to define where an app would be installed; I don't think that's a problem with Nexus currently?

**Comment by Raymo111** [comment]
> > `$XDG_CONFIG_HOME` on *nix
> 
> It should be `$XDG_DATA_HOME` for anything that isn't configuration. Ideally, we should not store configuration and the state of the app (chord logs in this case) in the same database.
> 
> So, ideally, config would go into `$XDG_CONFIG_HOME/nexus.conf` and any data/state will go in `$XDG_DATA_HOME/nexus/`.

Fair point for DATA instead of CONFIG, but separating config and data will have to be another feature, as they're currently in one SQL file.

> > on *nix
> 
> Also, this is for Linux, not just NixOS :P

It isn't just for Linux: https://en.m.wiktionary.org/wiki/*nix

**Comment by Raymo111** [comment]
> Also, @jdestgermain, what's wrong with the current exe approach? I'm personally biased against installers as they provide little value. The most significant thing I'd say installers help in is to define where an app would be installed; I don't think that's a problem with Nexus currently?

I don't believe you use Windows? On Windows using APPDATA with portable executables is frowned upon, and it's the standard for data-persistent applications to come with an installer on both Windows and MacOS (as well in *nix with package managers). This also makes upgrades easier, since users won't have to manually download new executables every time we have an upgrade, which may discourage them from upgrading.

**Comment by GetPsyched** [comment]
> > > `$XDG_CONFIG_HOME` on *nix
> > 
> > 
> > It should be `$XDG_DATA_HOME` for anything that isn't configuration. Ideally, we should not store configuration and the state of the app (chord logs in this case) in the same database.
> > So, ideally, config would go into `$XDG_CONFIG_HOME/nexus.conf` and any data/state will go in `$XDG_DATA_HOME/nexus/`.
> 
> Fair point for DATA instead of CONFIG, but separating config and data will have to be another feature, as they're currently in one SQL file.

Yes, just noting that it should be done; in the future if not right now.

> > > on *nix
> > 
> > 
> > Also, this is for Linux, not just NixOS :P
> 
> It isn't just for Linux: https://en.m.wiktionary.org/wiki/*nix

Apologies, I didn't notice that you used the asterisk as a wildcard.

**Comment by GetPsyched** [comment]
> > Also, @jdestgermain, what's wrong with the current exe approach? I'm personally biased against installers as they provide little value. The most significant thing I'd say installers help in is to define where an app would be installed; I don't think that's a problem with Nexus currently?
> 
> I don't believe you use Windows? On Windows using APPDATA with portable executables is frowned upon, and it's the standard for data-persistent applications to come with an installer on both Windows and MacOS (as well in *nix with package managers). This also makes upgrades easier, since users won't have to manually download new executables every time we have an upgrade, which may discourage them from upgrading.

Fair enough! I did not know about those standards; thanks.

**Comment by Raymo111** [comment]
Given bug #7, the pre-beta scope for this issue is:
- Create a Windows installer that installs the unpacked PyInstaller-generated sources and executable into `C:\Program Files` or some similarly relevant directory
  - Have options to create start menu and desktop shortcuts
- Change the default path to the SQLite file to be platform dependent
  - on *nix: `$XDG_DATA_HOME/nexus/` (create this directory, with `$XDG_DATA_HOME` defaulting to `$HOME/.local/share` if it is not defined, in accordance with the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html))
  - on Windows: `%APPDATA%\CharaChorder\nexus\` (create this directory)
